name: build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        include:
          - os: ubuntu-22.04
            os-name: ubuntu
            package-manager: apt
          - os: macos-14
            os-name: macos
            package-manager: brew
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up dependencies (Ubuntu)
        if: matrix.os-name == 'ubuntu'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq \
            libfftw3-dev \
            ninja-build \
            libsndfile1-dev \
            meson

      - name: Set up dependencies (macOS)
        if: matrix.os-name == 'macos'
        run: |
          brew update
          brew install fftw ninja libsndfile meson

      - name: Configure build
        run: |
          meson setup build \
            --buildtype=release \
            -Denable_examples=true

      - name: Build library
        run: |
          meson compile -C build -v

      - name: Build examples
        run: |
          meson compile -C build -v
