name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq \
            libfftw3-dev \
            ninja-build \
            libsndfile1-dev \
            meson \
            gcovr

      - name: Configure build
        run: |
          meson setup build \
            --buildtype=debug \
            -Denable_examples=true \
            -Denable_tests=true \
            -Db_coverage=true

      - name: Build project
        run: |
          meson compile -C build -v

      - name: Run tests
        run: |
          meson test -C build

      - name: Generate coverage report
        run: |
          ninja -C build coverage-xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/meson-logs/coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
